start_manual_watering:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: false
          filter:
            - integration: soilsync
    duration:
      required: true
      selector:
        number:
          min: 1
          max: 7200
          unit_of_measurement: s
          mode: box

stop_watering:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: false
          filter:
            - integration: soilsync

evaluate_zone:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: false
          filter:
            - integration: soilsync

clear_fault:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: false
          filter:
            - integration: soilsync
